### ISSUE TITLE
[RFC] Switch to HoaCompiler?

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#215]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | no
| BC Break report?      | no
| RFC?                  | yes

@sstok what do you think about using https://github.com/hoaproject/Compiler instead of in-house solution? It might provide some opportunities that go beyong #185 or or #23.

**Comment by sstok** [comment]
Thanks for the suggestion, I actually looked at a number of parsers and compilers when writing the Lexer for string-input but most of them use a tokenizer approach where you can easily run into a number of issues.

The String syntax is not regular (unless values are quoted), and because everything is parsed as a whole it's really difficult to show user-friendly errors https://github.com/rollerworks/search/issues/74

The current Lexer was inspired on the Symfony/Dotenv component because it allows for some really user friendly error messages and doesn't ignore spaces between characters (this a really big issues with most parsers).

The HoaCompiler uses AST which actually poses another challenge as you first transform it an AST, and then you need to traverse the AST to extract structure and values (and find common errors). AST is great for analyzing and transpiling. But less usable for processing a string into something completely else 😋

**Comment by dkarlovi** [comment]
Thanks for the in-depth explanation! :+1:
