### ISSUE TITLE
Add support to "search anything"

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#230]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

See https://github.com/rollerworks/search/issues/23#issuecomment-339689378

> For example, let's say I have a bunch of articles. I'd like to find stuff about Paris so I can do
> ```
> title: ~*paris; body: ~*paris; etc: ~*paris; date: > 2010-01-01
> ```
> What I'd actually want is to say
> ```
> paris; date: > 2010-01-01
> ```
> What would be a good way to do this? It would basically be an unbound query which could/should be bound like above. Would what even be possible?
> Edit: [Elasticsearch supports that concept with the `default_field` property](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html).

**Comment by dkarlovi** [comment]
@sstok I'd probably work on this soon, do you have any guidelines or ideas how to get there?

**Comment by sstok** [comment]
A default field should not be to difficult to add (given it's separate from fields), but I wonder about some edge cases 🤔

- Should a subgroup allow a default field? (technically possible but might be a bit confusing from the user perspective)
- What if the SmartQuery is used, I thought of instead of having a separate StringInput to integrate the SmartQuery into the StringQuery; If you provide a value (without a field) will it check all the fields, or always use the default field?
- Should this be used instead of StringQuery as it's more predictable?

PS. SmartQuery could be better renamed to SmartSearch.

**Comment by dkarlovi** [comment]
I think it would make sense to allow default field(s) explicitly and not just convert to an array. This allows the underlying system to handle it better if it's able to (see Elasticsearch example).

Not sure I understand your questions, could you give a short example for each point?
